### ISSUE TITLE
Left join not working when using DocumentTypeFilter

### ISSUE THREAD

**Issue by timtim002hk** [couchbaselabs/Linq2Couchbase#199] opened 2017-06-03 15:29 UTC
Left join not working, when i using DocumentTypeFilter. I would like to know how to fix this problem without remove DocumentTypeFilter.

**My Linq**:
var query = from s in context.Query<User>()
        join c in context.Query<Country>() on s.CountryKey equals Couchbase.Linq.N1QlFunctions.Key(c) into cg
        from c in cg.DefaultIfEmpty()
        select new { User = s, Country = c };

**Generated Statement**
SELECT `Extent1` as `User`, `Extent2` as `Country` FROM `courage` as `Extent1` LEFT JOIN `courage` as `Extent2` ON KEYS `Extent1`.`countryKey` WHERE (`Extent1`.`type` = 'user') AND (`Extent2`.`type` = 'country')

**Correct Statement**
SELECT `Extent1` as `User`, `Extent2` as `Country` FROM `courage` as `Extent1` LEFT JOIN `courage` as `Extent2` ON KEYS `Extent1`.`countryKey` WHERE (`Extent1`.`type` = 'user')

**Comment by brantburnett** [comment] 2017-06-03 19:07
@timtim002hk 

Based on your question, I'm guessing the problem is that the Extent2.type = 'country' filter is being applied after the join rather than before the join.  This is causing it to behave like an inner join instead of like a left join?

If so, that is, unfortunately, a known limitation currently: https://github.com/brantburnett/Linq2Couchbase/blob/master/Src/Couchbase.Linq/QueryGeneration/N1QLQueryModelVisitor.cs#L909

First of all, having an `Extent2.type = 'country'` clause is accurate, based on the LINQ statement being processed.  The presence of the DocumentTypeFilter means that some kind of filter is requested and should be present.  The issue is that it isn't being applied correctly.

Basically, I'm not certain of a way to actually replicate the desired behavior with N1QL.  It's a limitation of the ON KEYS clause for LEFT JOINs that you can't apply additional filtering before the join is processed.  But this filter is something included in the LINQ statement, so the query generator is making a best effort to include it in the query (in an incorrect way in this case).

A few ideas I've considered:
1. Ignore filter clauses before the join (seems like poor form)
2. Provide an overload of the Query method with an option to suppress filters which you can use if you're doing joins
3. Find some way to provide the behavior described in LINQ using a construct other than a JOIN (may not be possible or may be very messy)
4. Apply a minor alteration to the WHERE clause for filters applied before a LEFT JOIN, something like `AND (Extent1 IS NULL OR Extent1.type = 'country')`.

I'll poke around at it some and see what if I can get something working.

**Comment by brantburnett** [comment] 2017-06-03 20:35
@timtim002hk 

I was unable to find a way to build a N1QL query with the document type filter still applied to the right side of the join.  There just doesn't seem to be a parallel for that LINQ construct.

Instead of applying a change that only made the generated N1QL query partially correct, instead I've added an option to suppress the filters on the right side of the join expression in LINQ.  This way the generated LINQ expression tree and N1QL query will be in sync, and will match the statement you listed above as the "Correct Statement".

This change is in pull request #200.

Thanks,
Brant

**Comment by timtim002hk** [comment] 2017-06-04 03:51
So i temporarily remove DocumentTypeFilter and  look forward to the next official update.
Thank you very much for your detailed answer. ^o^

**Closed** 2017-06-04 21:45 UTC
