### ISSUE TITLE
String Operator Issues

### ISSUE THREAD

**Issue by Pierl0** [couchbaselabs/Linq2Couchbase#215] opened 2017-09-19 13:42 UTC
Hello, 

We have an issue using .Contains(), .ToUpper(), .ToLower() inside Linq request for couchbase. 

Example : 
```
          var result = (from prod in context.Query<Product>()
                                       where productList.Contains(prod.Code)
                                       && prod.Site == siteCode
                                       select prod );
```

produces the error 

> The type initializer for 'Couchbase.Linq.QueryGeneration.MethodCallTranslators.StringTrimMethodCallTranslator' threw an exception. 

Thanks for your answer.

**Comment by brantburnett** [comment] 2017-09-19 14:17
@Pierl0 

This is currently an issue when using .NET Core 2.0.  A fix has already been merged and will be included in the next release.  It was caused by some additional overloaded method signatures add to System.String in .NET Core 2.0.

At the moment, the only workaround is to target .NET Core 1.1 or use a custom version of Linq2Couchbase built manually from the master branch.

**Comment by Pierl0** [comment] 2017-09-19 14:59
@brantburnett 

Thanks, do you know when the next release will be available ?

**Comment by jeffrymorris** [comment] 2017-09-20 22:45
@Pierl0 -

We'll be pushing 1.3.3 release with support for .NET Core 2.0 in the couple of days; we will release 1.4.0 with full support for Couchbase Server 5.0 some time before Connect 2017 on Oct 25th-26th.

**Comment by brantburnett** [comment] 2017-09-26 00:36
@Pierl0 

Release 1.3.3 is available here: https://www.nuget.org/packages/Linq2Couchbase/1.3.3

Thanks @jeffrymorris for putting it together.

**Comment by Pierl0** [comment] 2017-09-28 07:17
@brantburnett @jeffrymorris 
hello, thnaks for the answer we will try the new version in the day

**Closed** 2017-10-23 16:08 UTC
