### ISSUE TITLE
_cachedKeyProperties in BucketContext class could be static to run faster !!??

### ISSUE THREAD

**Issue by lpyedge** [couchbaselabs/Linq2Couchbase#219] opened 2017-11-06 10:47 UTC
_cachedKeyProperties in BucketContext class could be static to run faster !!??

**Comment by brantburnett** [comment] 2017-11-07 22:06
@lpyedge 

Good catch, it was intended to be but it looks like it was overlooked.  Thanks for bringing it to our attention.

**Comment by MikeGoldsmith** [comment] 2017-11-21 12:00
Closing this issue as the fix to make CackedKeyProperties static has been merged.

**Closed by MikeGoldsmith** 2017-11-21 12:00 UTC
